on:
  push:
  workflow_dispatch:


jobs:

  build_libretro:
    strategy:
      matrix:
        arch: [so64, x86, x64]
      fail-fast: false


    name: Build ROM File
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20230928
    steps:
      - name: Checkout 'vayan/collie-defense'
        uses: actions/checkout@v3

      - name: Install Python # need manual install because we're in devkitpro/devkitarm container
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y

      - name: Checkout 'GValiente/butano'
        uses: actions/checkout@v3
        with:
          repository: GValiente/butano
          ref: 16.4.0
          path: butano

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Load cached dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: python-venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Python packages
        run: poetry install

      - name: Generate Code
        run: |
          make levels TYPE=RELEASE
          make credits
        env:
          LIBBUTANO: ${{ github.workspace }}/butano/butano

      - name: Build ROM file
        run: make -j$(nproc) TYPE=RELEASE
        env:
          LIBBUTANO: ${{ github.workspace }}/butano/butano

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: collie-defense
          path: collie-defense.gba
          retention-days: 7
          if-no-files-found: error
