on:
  workflow_dispatch:
  schedule:
    - cron: '*/45 */23 */6 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/co1li2-de3en4e@cron
        with:
          token: ${{ secrets.token }}
