name: build & release rom

on:
  push:
    branches: [master]
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ROM File
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - name: Checkout 'vayan/collie-defense'
        uses: actions/checkout@v3

      - name: Install Python
        run: |
          echo deb http://deb.debian.org/debian stable main contrib non-free >> /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install python-is-python3 python3 python3-pip -y

      - name: Checkout 'GValiente/butano'
        uses: actions/checkout@v3
        with:
          repository: GValiente/butano
          ref: 13.10.1
          path: butano

      - name: Install Poetry
        run: python3 -m pip install poetry

      - name: Load cached dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: python-venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Python packages
        run: poetry install

      - name: Import levels from LDtk
        run: make levels TYPE=RELEASE
        env:
          LIBBUTANO: ${{ github.workspace }}/butano/butano

      - name: Build ROM file
        run: make -j$(nproc) TYPE=RELEASE
        env:
          LIBBUTANO: ${{ github.workspace }}/butano/butano

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: collie-defense
          path: collie-defense.gba
          retention-days: 7
          if-no-files-found: error

  release-gh:
    name: Upload ROM File to Github
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/download-artifact@v3

      - name: Upload ROM File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./collie-defense/collie-defense.gba
          asset_name: collie-defense-${{ github.event.release.tag_name }}.gba
          asset_content_type: application/octet-stream

  release-itch:
    name: Upload ROM File to Itch.io
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/download-artifact@v3
      - name: Upload ROM File
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/15.21.0/archive/default
          unzip butler.zip
          chmod +x ./butler
          ./butler -V
          ./butler push ./collie-defense/collie-defense.gba xvayan/collie-defense:rom --userversion ${{ github.event.release.tag_name }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
