name: deploy web

on:
  push:
    branches: [master]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'web'
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
        id: deployment
        uses: actions/deploy-pages@v1
