# fly.toml app configuration file generated for collie-defense on 2023-06-29T14:56:15+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "collie-defense"
primary_region = "hkg"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
